const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_USER_FACEBOOK = "AUTH_USER_FACEBOOK";
const AUTH_USER_GOOGLE = "AUTH_USER_GOOGLE";
const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
const AUTH_USER_ERROR = "AUTH_USER_ERROR";
const ADD_WISHLIST_ID_TO_USER = "ADD_WISHLIST_ID_TO_USER";

export default {
  AUTH_LOGOUT,
  AUTH_USER_FACEBOOK,
  AUTH_USER_GOOGLE,
  AUTH_USER_SUCCESS,
  AUTH_USER_ERROR,
  ADD_WISHLIST_ID_TO_USER
};
