const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_LOGOUT_ERROR = "AUTH_LOGOUT_ERROR";
const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
const AUTH_USER_FACEBOOK = "AUTH_USER_FACEBOOK";
const AUTH_USER_GOOGLE = "AUTH_USER_GOOGLE";
const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
const AUTH_USER_ERROR = "AUTH_USER_ERROR";
const ADD_USER_TO_WISHLIST = "ADD_USER_TO_WISHLIST";
const ADD_USER_TO_WISHLIST_ERROR = "ADD_USER_TO_WISHLIST_ERROR";
const ADD_USER_TO_WISHLIST_SUCCESS = "ADD_USER_TO_WISHLIST_SUCCESS";
const REMOVE_USER_FROM_WISHLIST = "REMOVE_USER_FROM_WISHLIST";
const REMOVE_USER_FROM_WISHLIST_SUCCESS = "REMOVE_USER_FROM_WISHLIST_SUCCESS";
const REMOVE_USER_FROM_WISHLIST_ERROR = "REMOVE_USER_FROM_WISHLIST_ERROR";
const ADD_GROUP_ID_TO_USER = "ADD_GROUP_ID_TO_USER";
const REMOVE_GROUP_ID_FROM_USER = "REMOVE_GROUP_ID_FROM_USER";
const REMOVE_WISHLIST_ID_FROM_USER = "REMOVE_WISHLIST_ID_FROM_USER";
const ADD_WISHLIST_ID_TO_USER = "ADD_WISHLIST_ID_TO_USER";
const SEARCH_FOR_USERS_WITH_NAME = "SEARCH_FOR_USERS_WITH_NAME";
const SEARCH_FOR_USERS_WITH_NAME_ERROR = "SEARCH_FOR_USERS_WITH_NAME_ERROR";
const SEARCH_FOR_USERS_WITH_NAME_SUCCESS = "SEARCH_FOR_USERS_WITH_NAME_SUCCESS";
const CLEAR_SEARCH = "CLEAR_SEARCH";
const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export default {
  AUTH_LOGOUT,
  AUTH_LOGOUT_ERROR,
  AUTH_LOGOUT_SUCCESS,
  AUTH_USER_FACEBOOK,
  AUTH_USER_GOOGLE,
  AUTH_USER_SUCCESS,
  AUTH_USER_ERROR,
  ADD_USER_TO_WISHLIST,
  ADD_USER_TO_WISHLIST_ERROR,
  ADD_USER_TO_WISHLIST_SUCCESS,
  ADD_GROUP_ID_TO_USER,
  REMOVE_GROUP_ID_FROM_USER,
  REMOVE_WISHLIST_ID_FROM_USER,
  REMOVE_USER_FROM_WISHLIST,
  REMOVE_USER_FROM_WISHLIST_SUCCESS,
  REMOVE_USER_FROM_WISHLIST_ERROR,
  SEARCH_FOR_USERS_WITH_NAME,
  SEARCH_FOR_USERS_WITH_NAME_ERROR,
  SEARCH_FOR_USERS_WITH_NAME_SUCCESS,
  ADD_WISHLIST_ID_TO_USER,
  CLEAR_SEARCH,
  UPDATE_CURRENT_USER
};
