const AUTH_LOGOUT = "AUTH_LOGOUT";
const AUTH_USER_FACEBOOK = "AUTH_USER_FACEBOOK";
const AUTH_USER_GOOGLE = "AUTH_USER_GOOGLE";
const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
const AUTH_USER_ERROR = "AUTH_USER_ERROR";
const ADD_USER_TO_WISHLIST = "ADD_USER_TO_WISHLIST";
const ADD_USER_TO_WISHLIST_ERROR = "ADD_USER_TO_WISHLIST_ERROR";
const ADD_USER_TO_WISHLIST_SUCCESS = "ADD_USER_TO_WISHLIST_SUCCESS";

export default {
  AUTH_LOGOUT,
  AUTH_USER_FACEBOOK,
  AUTH_USER_GOOGLE,
  AUTH_USER_SUCCESS,
  AUTH_USER_ERROR,
  ADD_USER_TO_WISHLIST,
  ADD_USER_TO_WISHLIST_ERROR,
  ADD_USER_TO_WISHLIST_SUCCESS
};
