const CREATE_GROUP_WISHLIST_ITEM = "CREATE_GROUP_WISHLIST_ITEM";
const CREATE_GROUP_WISHLIST_ITEM_SUCCESS = "CREATE_GROUP_WISHLIST_ITEM_SUCCESS";
const CREATE_GROUP_WISHLIST_ITEM_ERROR = "CREATE_GROUP_WISHLIST_ITEM_ERROR";

const FETCH_ALL_GROUP_ITEMS = "FETCH_ALL_GROUP_ITEMS";
const FETCH_ALL_GROUP_ITEMS_SUCCESS = "FETCH_ALL_GROUP_ITEMS_SUCCESS";
const FETCH_ALL_GROUP_ITEMS_ERROR = "FETCH_ALL_GROUP_ITEMS_ERROR";

const EDIT_GROUP_WISHLIST_ITEM = "EDIT_GROUP_WISHLIST_ITEM";
const EDIT_GROUP_WISHLIST_ITEM_SUCCESS = "EDIT_GROUP_WISHLIST_ITEM_SUCCESS";
const EDIT_GROUP_WISHLIST_ITEM_ERROR = "EDIT_GROUP_WISHLIST_ITEM_ERROR";

const CLAIM_GROUP_WISHLIST_ITEM = "CLAIM_GROUP_WISHLIST_ITEM";
const CLAIM_GROUP_WISHLIST_ITEM_SUCCESS = "CLAIM_GROUP_WISHLIST_ITEM_SUCCESS";
const CLAIM_GROUP_WISHLIST_ITEM_ERROR = "CLAIM_GROUP_WISHLIST_ITEM_ERROR";

const UNCLAIM_GROUP_WISHLIST_ITEM = "UNCLAIM_GROUP_WISHLIST_ITEM";
const UNCLAIM_GROUP_WISHLIST_ITEM_SUCCESS =
  "UNCLAIM_GROUP_WISHLIST_ITEM_SUCCESS";
const UNCLAIM_GROUP_WISHLIST_ITEM_ERROR = "UNCLAIM_GROUP_WISHLIST_ITEM_ERROR";

export default {
  CREATE_GROUP_WISHLIST_ITEM,
  CREATE_GROUP_WISHLIST_ITEM_SUCCESS,
  CREATE_GROUP_WISHLIST_ITEM_ERROR,

  FETCH_ALL_GROUP_ITEMS,
  FETCH_ALL_GROUP_ITEMS_SUCCESS,
  FETCH_ALL_GROUP_ITEMS_ERROR,

  EDIT_GROUP_WISHLIST_ITEM,
  EDIT_GROUP_WISHLIST_ITEM_SUCCESS,
  EDIT_GROUP_WISHLIST_ITEM_ERROR,

  CLAIM_GROUP_WISHLIST_ITEM,
  CLAIM_GROUP_WISHLIST_ITEM_ERROR,
  CLAIM_GROUP_WISHLIST_ITEM_SUCCESS,

  UNCLAIM_GROUP_WISHLIST_ITEM,
  UNCLAIM_GROUP_WISHLIST_ITEM_ERROR,
  UNCLAIM_GROUP_WISHLIST_ITEM_SUCCESS
};
