const CREATE_USER_WISHLIST = "CREATE_USER_WISHLIST";
const CREATE_USER_WISHLIST_ERROR = "CREATE_USER_WISHLIST_ERROR";
const CREATE_USER_WISHLIST_SUCCESS = "CREATE_USER_WISHLIST_SUCCESS";

export default {
  CREATE_USER_WISHLIST,
  CREATE_USER_WISHLIST_ERROR,
  CREATE_USER_WISHLIST_SUCCESS
};
