const CREATE_USER_WISHLIST = "CREATE_USER_WISHLIST";
const CREATE_USER_WISHLIST_ERROR = "CREATE_USER_WISHLIST_ERROR";
const CREATE_USER_WISHLIST_SUCCESS = "CREATE_USER_WISHLIST_SUCCESS";

const FETCH_OWNED_WISHLISTS = "FETCH_OWNED_WISHLISTS";
const FETCH_OWNED_WISHLISTS_ERROR = "FETCH_OWNED_WISHLISTS_ERROR";
const FETCH_OWNED_WISHLISTS_SUCCESS = "FETCH_OWNED_WISHLISTS_SUCCESS";

const FETCH_WISHLISTS = "FETCH_WISHLISTS";
const FETCH_WISHLISTS_ERROR = "FETCH_WISHLISTS_ERROR";
const FETCH_WISHLISTS_SUCCESS = "FETCH_WISHLISTS_SUCCESS";

export default {
  CREATE_USER_WISHLIST,
  CREATE_USER_WISHLIST_ERROR,
  CREATE_USER_WISHLIST_SUCCESS,
  FETCH_OWNED_WISHLISTS,
  FETCH_OWNED_WISHLISTS_ERROR,
  FETCH_OWNED_WISHLISTS_SUCCESS,
  FETCH_WISHLISTS,
  FETCH_WISHLISTS_ERROR,
  FETCH_WISHLISTS_SUCCESS
};
