const CREATE_USER_WISHLIST = "CREATE_USER_WISHLIST";
const CREATE_USER_WISHLIST_ERROR = "CREATE_USER_WISHLIST_ERROR";
const CREATE_USER_WISHLIST_SUCCESS = "CREATE_USER_WISHLIST_SUCCESS";

const FETCH_WISHLISTS = "CREATE_USER_WISHLIST";
const FETCH_WISHLISTS_ERROR = "CREATE_USER_WISHLIST_ERROR";
const FETCH_WISHLISTS_SUCCESS = "CREATE_USER_WISHLIST_SUCCESS";

export default {
  CREATE_USER_WISHLIST,
  CREATE_USER_WISHLIST_ERROR,
  CREATE_USER_WISHLIST_SUCCESS,
  FETCH_WISHLISTS,
  FETCH_WISHLISTS_ERROR,
  FETCH_WISHLISTS_SUCCESS
};
