const GET_USERS_WITH_UID = "GET_USERS_WITH_UID";
const GET_USERS_WITH_UID_SUCCESS = "GET_USERS_WITH_UID_SUCCESS";
const GET_USERS_WITH_UID_ERROR = "GET_USERS_WITH_UID_ERROR";

export default {
  GET_USERS_WITH_UID,
  GET_USERS_WITH_UID_SUCCESS,
  GET_USERS_WITH_UID_ERROR
};
