const GET_USERS_WITH_UIDS = "GET_USERS_WITH_UIDS";
const GET_USERS_WITH_UIDS_SUCCESS = "GET_USERS_WITH_UIDS_SUCCESS";
const GET_USERS_WITH_UIDS_ERROR = "GET_USERS_WITH_UIDS_ERROR";

export default {
  GET_USERS_WITH_UIDS,
  GET_USERS_WITH_UIDS_SUCCESS,
  GET_USERS_WITH_UIDS_ERROR
};
