const GET_USERS_WITH_UIDS = "GET_USERS_WITH_UIDS";
const GET_USERS_WITH_UIDS_SUCCESS = "GET_USERS_WITH_UIDS_SUCCESS";
const GET_USERS_WITH_UIDS_ERROR = "GET_USERS_WITH_UIDS_ERROR";
const CACHE_USER = "CACHE_USER";
const CACHE_USER_SUCCESS = "CACHE_USER_SUCCESS";
const CACHE_USER_ERROR = "CACHE_USER_ERROR";

export default {
  GET_USERS_WITH_UIDS,
  GET_USERS_WITH_UIDS_SUCCESS,
  GET_USERS_WITH_UIDS_ERROR,
  CACHE_USER_ERROR,
  CACHE_USER_SUCCESS,
  CACHE_USER
};
