const CREATE_CHAT = "CREATE_CHAT";
const CREATE_CHAT_ERROR = "CREATE_CHAT_ERROR";
const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";

const LOAD_CHAT = "LOAD_CHAT";
const LOAD_CHAT_ERROR = "LOAD_CHAT_ERROR";
const LOAD_CHAT_SUCCESS = "LOAD_CHAT_SUCCESS";

const SEND_CHAT_MESSAGE = "SEND_CHAT_MESSAGE";
const SEND_CHAT_MESSAGE_ERROR = "SEND_CHAT_MESSAGE_ERROR";
const SEND_CHAT_MESSAGE_SUCCESS = "SEND_CHAT_MESSAGE_SUCCESS";

const DELETE_CHAT = "DELETE_CHAT";
const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
const DELETE_CHAT_ERROR = "DELETE_CHAT_ERROR";

export default {
  CREATE_CHAT,
  CREATE_CHAT_ERROR,
  CREATE_CHAT_SUCCESS,
  LOAD_CHAT,
  LOAD_CHAT_ERROR,
  LOAD_CHAT_SUCCESS,
  SEND_CHAT_MESSAGE,
  SEND_CHAT_MESSAGE_ERROR,
  SEND_CHAT_MESSAGE_SUCCESS,
  DELETE_CHAT,
  DELETE_CHAT_ERROR,
  DELETE_CHAT_SUCCESS
};
