
const types = {
  FETCH_ALL_USER_GROUPS : "FETCH_ALL_USER_GROUPS",
  FETCH_ALL_USER_GROUPS_ERROR : "FETCH_ALL_USER_GROUPS_ERROR",
  CREATE_GROUP : "CREATE_GROUP",
  CREATE_GROUP_ERROR : "CREATE_GROUP_ERROR",
  INVITE_USER_TO_GROUP : "INVITE_USER_TO_GROUP",
  INVITE_USER_TO_GROUP_ERROR : "INVITE_USER_TO_GROUP_ERROR",
  REMOVE_USER_FROM_GROUP : "REMOVE_USER_FROM_GROUP",
  REMOVE_USER_FROM_GROUP_ERROR : "REMOVE_USER_FROM_GROUP_ERROR"
};

export default types;
