const FETCH_ALL_USER_GROUPS = "FETCH_ALL_USER_GROUPS";
const FETCH_ALL_USER_GROUPS_ERROR = "FETCH_ALL_USER_GROUPS_ERROR";
const FETCH_ALL_USER_GROUPS_SUCCESS = "FETCH_ALL_USER_GROUPS_SUCCESS";
const CREATE_GROUP = "CREATE_GROUP";
const CREATE_GROUP_ERROR = "CREATE_GROUP_ERROR";
const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
const INVITE_USER_TO_GROUP = "INVITE_USER_TO_GROUP";
const INVITE_USER_TO_GROUP_ERROR = "INVITE_USER_TO_GROUP_ERROR";
const INVITE_USER_TO_GROUP_SUCCESS = "INVITE_USER_TO_GROUP_SUCCESS";
const REMOVE_USER_FROM_GROUP = "REMOVE_USER_FROM_GROUP";
const REMOVE_USER_FROM_GROUP_ERROR = "REMOVE_USER_FROM_GROUP_ERROR";
const REMOVE_USER_FROM_GROUP_SUCCESS = "REMOVE_USER_FROM_GROUP_SUCCESS";
const UPDATE_CURRENT_GROUP = "UPDATE_CURRENT_GROUP";

export default {
  FETCH_ALL_USER_GROUPS,
  FETCH_ALL_USER_GROUPS_ERROR,
  FETCH_ALL_USER_GROUPS_SUCCESS,
  CREATE_GROUP,
  CREATE_GROUP_ERROR,
  CREATE_GROUP_SUCCESS,
  INVITE_USER_TO_GROUP,
  INVITE_USER_TO_GROUP_ERROR,
  INVITE_USER_TO_GROUP_SUCCESS,
  REMOVE_USER_FROM_GROUP,
  REMOVE_USER_FROM_GROUP_ERROR,
  REMOVE_USER_FROM_GROUP_SUCCESS,
  UPDATE_CURRENT_GROUP
};
