const CREATE_WISHLIST_ITEM = "CREATE_WISHLIST_ITEM";
const CREATE_WISHLIST_ITEM_SUCCESS = "CREATE_WISHLIST_ITEM_SUCCESS";
const CREATE_WISHLIST_ITEM_ERROR = "CREATE_WISHLIST_ITEM_ERROR";
const FETCH_ALL_ITEMS = "FETCH_ALL_ITEMS";
const FETCH_ALL_ITEMS_SUCCESS = "FETCH_ALL_ITEMS_SUCCESS";
const FETCH_ALL_ITEMS_ERROR = "FETCH_ALL_ITEMS_ERROR";
const EDIT_WISHLIST_ITEM = "EDIT_WISHLIST_ITEM";
const EDIT_WISHLIST_ITEM_SUCCESS = "EDIT_WISHLIST_ITEM_SUCCESS";
const EDIT_WISHLIST_ITEM_ERROR = "EDIT_WISHLIST_ITEM_ERROR";
const CLAIM_WISHLIST_ITEM = "CLAIM_WISHLIST_ITEM";
const CLAIM_WISHLIST_ITEM_SUCCESS = "CLAIM_WISHLIST_ITEM_SUCCESS";
const CLAIM_WISHLIST_ITEM_ERROR = "CLAIM_WISHLIST_ITEM_ERROR";

export default {
  CREATE_WISHLIST_ITEM,
  CREATE_WISHLIST_ITEM_SUCCESS,
  CREATE_WISHLIST_ITEM_ERROR,
  FETCH_ALL_ITEMS,
  FETCH_ALL_ITEMS_SUCCESS,
  FETCH_ALL_ITEMS_ERROR,
  EDIT_WISHLIST_ITEM,
  EDIT_WISHLIST_ITEM_SUCCESS,
  EDIT_WISHLIST_ITEM_ERROR,
  CLAIM_WISHLIST_ITEM,
  CLAIM_WISHLIST_ITEM_SUCCESS,
  CLAIM_WISHLIST_ITEM_ERROR
};
