const FETCH_ALL_ITEMS = "FETCH_ALL_ITEMS";
const FETCH_ALL_ITEMS_SUCCESS = "FETCH_ALL_ITEMS_SUCCESS";
const FETCH_ALL_ITEMS_ERROR = "FETCH_ALL_ITEMS_ERROR";

export default {
  FETCH_ALL_ITEMS,
  FETCH_ALL_ITEMS_SUCCESS,
  FETCH_ALL_ITEMS_ERROR
}